"use client";
import Link from "next/link";
import "./globals.css";
import { usePathname } from "next/navigation";
// export const metadata = {
//   // title: "prep",
//   title: {
//     // absolute: "",
//     default: "prep",
//     template: "%s | prep",
//   },
//   // discription: "generated byy mee",
// };
export default function RootLayout({ children }) {
  const pathName = usePathname();
  console.log(pathName);

  return (
    <html lang="en">
      <body>
        <nav className="bg-slate-100 text-blue-400 p-5">
          <ul className="flex gap-10 list-none font-semibold text-xl">
            <Link
              href={"/"}
              className={`${
                pathName === "/" ? "bg-slate-300" : ""
              } bg-slate-100 text-blue-400 p-1`}
            >
              home
            </Link>
            <Link href={"/products"}>products</Link>
            <Link href={"/login"}>auth</Link>
            <Link href={"/about"}>about</Link>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
