import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "auth-js practise",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased bg-stone-100 text-stone-600`}>
        {children}
      </body>
    </html>
  );
}
